AdsManagement/Controllers/AdsController.cs
using AdsManagement.DAL.Models;
using AdsManagement.DAL.Repository;
using AdsManagement.Models;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdsManagement.Controllers
{
    public class AdsController : BaseController
    {
        private IAdsManagementRepository<Offer> _repository;
        public AdsController()
        {
            _repository = this.m_Repository;
        }
        // GET: Ads
        public ActionResult Index()
        {
            List<Offer> data = _repository.LoadList(opt => opt.EndDate >= DateTime.Now).ToList();
            var afterMap = Mapper.Map<List<OffersViewModel>>(data);
            return View(afterMap);
        }

        public ActionResult ShowAdsByCategory(int categoryId = 1)
        {
            List<Offer> data = _repository.LoadList(opt => opt.EndDate >= DateTime.Now && opt.Category.Id == categoryId).ToList();
            var afterMap = Mapper.Map<List<OffersViewModel>>(data);
            return View(afterMap);
        }

        public ActionResult AddOffer()
        {
            List<OfferCategory> data = _repository.LoadList(opt => opt.EndDate >= DateTime.Now).Select(x => x.Category).ToList();
            List<SelectListItem> listItems = new List<SelectListItem>();
            foreach (var item in data)
            {
                listItems.Add(
                    new SelectListItem
                    {
                        Text = item.Name,
                        Value = item.Id.ToString(),
                        Selected = item.Id == 1 ? true : false
                    });
            }
            var model = new OffersViewModel()
            {
                Categories = listItems
            };

            return View(model); 
        }
        [HttpPost]
        public ActionResult AddOffer(OffersViewModel model)
        {
            var afterMap = Mapper.Map<Offer>(model);
            _repository.Save(afterMap);
            return RedirectToAction("Index");
        }
    }
}

AdsManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ads Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ads Management", "Index", "Ads", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ads Management</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>